# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
    ]
